/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PhysicalTherapy;

import Business.EcoSystem;
import Business.Organization.HospitalOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.Patient.PatientAppointmentJPanel;

/**
 *
 * @author sonal
 */
public class PhysicalTherapyWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
EcoSystem business;
HospitalOrganization organization;
UserAccount account;

    /**
     * Creates new form PhysicalTherapyWorkAreaJPanel
     */
    public PhysicalTherapyWorkAreaJPanel(  JPanel userProcessContainer,EcoSystem business, HospitalOrganization organization,UserAccount account) {
        initComponents();
        this.business=business;
        this.organization=organization;
        this.userProcessContainer=userProcessContainer;
        this.account=account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel1.setText("Physical Therapy Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 63, -1, -1));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Manage Patients");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 152, 261, 58));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/maxresdefault.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -210, 3000, 1500));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManagePatientJPanel mpjp = new  ManagePatientJPanel( userProcessContainer,business,organization,account);
        userProcessContainer.add("ClinicManageEmployeeJPanel", mpjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
