/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkAreas;

import Business.EcoSystem;
import Business.Sytem.Conditions;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.concurrent.locks.Condition;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import utility.Validator;

/**
 *
 * @author sonal
 */
public class ManageConditionJpanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem system;

    /**
     * Creates new form ManageConditionJpanel
     */
    ManageConditionJpanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateDiseaseTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisease = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblwelcome = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        txtVaccineName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        conErrLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDisease.setBackground(new java.awt.Color(36, 47, 65));
        tblDisease.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblDisease.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        tblDisease.setForeground(new java.awt.Color(255, 255, 255));
        tblDisease.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Condition Name", "Condition ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDisease);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 263, 590, 170));

        btnNew.setBackground(new java.awt.Color(36, 47, 65));
        btnNew.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setText("Add a condition");
        btnNew.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnNew.setBorderPainted(false);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 170, 60));

        btnBack.setBackground(new java.awt.Color(36, 47, 65));
        btnBack.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 334, 110, 40));

        lblwelcome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(lblwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(2411, 16, 240, 20));

        btnDelete.setBackground(new java.awt.Color(36, 47, 65));
        btnDelete.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Remove Condition");
        btnDelete.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDelete.setBorderPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 610, 170, 60));

        txtVaccineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVaccineNameActionPerformed(evt);
            }
        });
        txtVaccineName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVaccineNameKeyPressed(evt);
            }
        });
        add(txtVaccineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 220, -1));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, -1, -1));

        conErrLbl.setForeground(new java.awt.Color(255, 51, 51));
        add(conErrLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, 270, 20));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Health Conditions");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/ekg.jpeg"))); // NOI18N
        jLabel6.setText("jLabel3");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2500, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:

        if (txtVaccineName.getText().equals("") || !system.getConditionsList().isUniqueCondition(txtVaccineName.getText())) {
            if (!system.getConditionsList().isUniqueCondition(txtVaccineName.getText())) {
                conErrLbl.setText("This condition already exists.");
            }
            if (txtVaccineName.getText().equals("")) {
                conErrLbl.setText("Cant leave condition blank.");
            }
            txtVaccineName.setBorder(new LineBorder(Color.red));
        } else {
            conErrLbl.setText("");
            txtVaccineName.setBorder(new LineBorder(Color.black));
            Conditions c = system.getConditionsList().addCondition();
            c.setDiseaseName(txtVaccineName.getText());
            populateDiseaseTable();
            txtVaccineName.setText("");
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDisease.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            Conditions p = (Conditions) tblDisease.getValueAt(selectedRow, 0);

            system.getConditionsList().removeCondition(p);
            JOptionPane.showMessageDialog(null, "You have successfully deleted the condition");
            populateDiseaseTable();
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtVaccineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVaccineNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtVaccineNameActionPerformed

    private void txtVaccineNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVaccineNameKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtVaccineName);
    }//GEN-LAST:event_txtVaccineNameKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel conErrLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JTable tblDisease;
    private javax.swing.JTextField txtVaccineName;
    // End of variables declaration//GEN-END:variables

    public void populateDiseaseTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblDisease.getModel();
        dtm.setRowCount(0);
        for (Conditions disease : system.getConditionsList().getConditionList()) {
            Object[] row = new Object[2];
            row[0] = disease;
            row[1] = disease.getDiseaseId();
            dtm.addRow(row);
        }
    }
}
