/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */
package userinterface.SystemAdminWorkAreas;

import userinterface.CountryAdminWorkAreas.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.NetworkCountry;
import Business.Network.NetworkState;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author raunak
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
    Color color1;

    //CountryNetwork cNetwork;
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        // this.cNetwork=cNetwork;
        populateTree();
    }

    public void populateTree() {

        DefaultTreeModel model = (DefaultTreeModel) JTree.getModel();

        ArrayList<NetworkCountry> cnetworkList = system.getNetworkCList();
        ArrayList<NetworkState> networkList;
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        NetworkCountry cNetwork;
        NetworkState network;
        Enterprise enterprise;
        Organization organization;

        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);

        DefaultMutableTreeNode cnetworkNode;
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        for (int h = 0; h < cnetworkList.size(); h++) {
            System.out.println("country"+ cnetworkList.get(h));
            cNetwork = cnetworkList.get(h);
            cnetworkNode = new DefaultMutableTreeNode(cNetwork.getName());
            networks.insert(cnetworkNode, h);

            networkList = cNetwork.getNetworkStateList();
            for (int i = 0; i < networkList.size(); i++) {
                System.out.println("state"+ networkList.get(i));
                network = networkList.get(i);
                networkNode = new DefaultMutableTreeNode(network.getName());
                cnetworkNode.insert(networkNode, i);

                enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();

                for (int j = 0; j < enterpriseList.size(); j++) {
                    System.out.println("enterprizse"+ enterpriseList.get(j));
                    enterprise = enterpriseList.get(j);
                    enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                    networkNode.insert(enterpriseNode, j);

                    organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
                    for (int k = 0; k < organizationList.size(); k++) {
                        organization = organizationList.get(k);
                        organizationNode = new DefaultMutableTreeNode(organization.getName());
                        enterpriseNode.insert(organizationNode, k);
                    }
                }
            }
        }

        model.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        manageNetworkJButton = new javax.swing.JButton();
        manageConditionsJPanel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        selectedNodeJLabel = new javax.swing.JLabel();
        manageAdminJButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setDividerSize(1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageNetworkJButton.setBackground(new java.awt.Color(36, 47, 65));
        manageNetworkJButton.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        manageNetworkJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkJButton.setText("Manage Network");
        manageNetworkJButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        manageNetworkJButton.setBorderPainted(false);
        manageNetworkJButton.setOpaque(false);
        manageNetworkJButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                manageNetworkJButtonFocusGained(evt);
            }
        });
        manageNetworkJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageNetworkJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageNetworkJButtonMouseExited(evt);
            }
        });
        manageNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageNetworkJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 179, 140));

        manageConditionsJPanel.setBackground(new java.awt.Color(36, 47, 65));
        manageConditionsJPanel.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        manageConditionsJPanel.setForeground(new java.awt.Color(255, 255, 255));
        manageConditionsJPanel.setText("Manage Condition");
        manageConditionsJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        manageConditionsJPanel.setBorderPainted(false);
        manageConditionsJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageConditionsJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageConditionsJPanelMouseExited(evt);
            }
        });
        manageConditionsJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageConditionsJPanelActionPerformed(evt);
            }
        });
        jPanel1.add(manageConditionsJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 179, 140));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Selected Node:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        selectedNodeJLabel.setFont(new java.awt.Font("Dubai Medium", 1, 13)); // NOI18N
        selectedNodeJLabel.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(selectedNodeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        manageAdminJButton1.setBackground(new java.awt.Color(36, 47, 65));
        manageAdminJButton1.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        manageAdminJButton1.setForeground(new java.awt.Color(255, 255, 255));
        manageAdminJButton1.setText("Manage Country Admin");
        manageAdminJButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        manageAdminJButton1.setBorderPainted(false);
        manageAdminJButton1.setOpaque(false);
        manageAdminJButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageAdminJButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageAdminJButton1MouseExited(evt);
            }
        });
        manageAdminJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdminJButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(manageAdminJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 179, 140));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(2000, 100));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 47, 65));
        jLabel2.setText("System Admin Work Area");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(jLabel2)
                .addContainerGap(1165, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2000, -1));

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(97, 212, 165));

        JTree.setBackground(new java.awt.Color(97, 212, 165));
        JTree.setFont(new java.awt.Font("Dubai Medium", 0, 13)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        JTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                valueChangedAction(evt);
            }
        });
        jScrollPane1.setViewportView(JTree);

        jPanel2.add(jScrollPane1);

        jSplitPane1.setLeftComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageConditionsJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageConditionsJPanelActionPerformed
        // TODO add your handling code here:
        ManageConditionJpanel manageConditionsJPanel = new ManageConditionJpanel(userProcessContainer, system);
        userProcessContainer.add("ManageCountryAdminJPanel", manageConditionsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageConditionsJPanelActionPerformed

    private void manageNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButtonActionPerformed
        ManageCountryNetworkJPanel manageNetworkJPanel = new ManageCountryNetworkJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageCountryNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButtonActionPerformed

    private void manageAdminJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdminJButton1ActionPerformed
        // TODO add your handling code here:
        ManageCountryAdminJPanel manageEnterpriseAdminJPanel = new ManageCountryAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageCountryAdminJPanel", manageEnterpriseAdminJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAdminJButton1ActionPerformed

    private void manageNetworkJButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manageNetworkJButtonFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_manageNetworkJButtonFocusGained

    private void manageNetworkJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageNetworkJButtonMouseEntered
        // TODO add your handling code here:
        System.out.println("Hovered here");
        color1 = manageNetworkJButton.getBackground();
        manageNetworkJButton.setBackground(Color.getHSBColor(102, 153, 300));
        
    }//GEN-LAST:event_manageNetworkJButtonMouseEntered

    private void manageNetworkJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageNetworkJButtonMouseExited
        // TODO add your handling code here:
           System.out.println("Hovered here");
        manageNetworkJButton.setBackground(color1);
    }//GEN-LAST:event_manageNetworkJButtonMouseExited

    private void manageAdminJButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAdminJButton1MouseEntered
        // TODO add your handling code here:
        System.out.println("Hovered here");
        color1 = manageAdminJButton1.getBackground();
        manageAdminJButton1.setBackground(Color.getHSBColor(102, 153, 300));
    }//GEN-LAST:event_manageAdminJButton1MouseEntered

    private void manageAdminJButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAdminJButton1MouseExited
        // TODO add your handling code here:
          System.out.println("Hovered here");
        manageAdminJButton1.setBackground(color1);
    }//GEN-LAST:event_manageAdminJButton1MouseExited

    private void manageConditionsJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageConditionsJPanelMouseEntered
        // TODO add your handling code here:
        System.out.println("Hovered here");
        color1 = manageConditionsJPanel.getBackground();
        manageConditionsJPanel.setBackground(Color.getHSBColor(102, 153, 300));
    }//GEN-LAST:event_manageConditionsJPanelMouseEntered

    private void manageConditionsJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageConditionsJPanelMouseExited
        // TODO add your handling code here:
              System.out.println("Hovered here");
        manageConditionsJPanel.setBackground(color1);
    }//GEN-LAST:event_manageConditionsJPanelMouseExited

    private void valueChangedAction(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_valueChangedAction
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) JTree.getLastSelectedPathComponent();
        if (selectedNode != null) {
            selectedNodeJLabel.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_valueChangedAction

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree JTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageAdminJButton1;
    private javax.swing.JButton manageConditionsJPanel;
    private javax.swing.JButton manageNetworkJButton;
    private javax.swing.JLabel selectedNodeJLabel;
    // End of variables declaration//GEN-END:variables
}
