/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */
package userinterface.CountryAdminWorkAreas;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.NetworkCountry;
import Business.Network.NetworkState;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;


/**
 *
 * @author raunak
 */
public class CountryAdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
    NetworkCountry cNetwork;
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public CountryAdminWorkAreaJPanel(JPanel userProcessContainer,UserAccount account, NetworkCountry cNetwork, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account= account;
        this.cNetwork=cNetwork;
       // this.cNetwork=new CountryNetwork();
        populateTree();
    }

    public void populateTree() {
        
        
        DefaultTreeModel model = (DefaultTreeModel) JTree.getModel();

        ArrayList<NetworkCountry> cnetworkList = system.getNetworkCList();
        ArrayList<NetworkState> networkList;
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        NetworkCountry cNetwork;
       
        NetworkState network;
        Enterprise enterprise;
        Organization organization;

        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);

        DefaultMutableTreeNode cnetworkNode;
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        for (int h = 0; h < cnetworkList.size(); h++) {
            if(account.getUsername().equalsIgnoreCase(cnetworkList.get(h).getName())){
            System.out.println("country"+ cnetworkList.get(h));
            cNetwork = cnetworkList.get(h);
            cnetworkNode = new DefaultMutableTreeNode(cNetwork.getName());
            
            networks.insert(cnetworkNode, 0);

            networkList = cNetwork.getNetworkStateList();
            for (int i = 0; i < networkList.size(); i++) {
                System.out.println("state"+ networkList.get(i));
                network = networkList.get(i);
                networkNode = new DefaultMutableTreeNode(network.getName());
                cnetworkNode.insert(networkNode, i);

                enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();

                for (int j = 0; j < enterpriseList.size(); j++) {
                    System.out.println("enterprizse"+ enterpriseList.get(j));
                    enterprise = enterpriseList.get(j);
                    enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                    networkNode.insert(enterpriseNode, j);

                    organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
                    for (int k = 0; k < organizationList.size(); k++) {
                        organization = organizationList.get(k);
                        organizationNode = new DefaultMutableTreeNode(organization.getName());
                        enterpriseNode.insert(organizationNode, k);
                    }
                }
            }
            }
        }

        model.reload();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        manageNetworkJButton = new javax.swing.JButton();
        manageOpoidListBtn = new javax.swing.JButton();
        manageEnterpriseJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        selectedNodeJLabel = new javax.swing.JLabel();
        manageEnterpriseAdminBtn = new javax.swing.JButton();
        mngPersonBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(150);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageNetworkJButton.setBackground(new java.awt.Color(36, 47, 65));
        manageNetworkJButton.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        manageNetworkJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkJButton.setText("Manage Network");
        manageNetworkJButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        manageNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageNetworkJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 70));

        manageOpoidListBtn.setBackground(new java.awt.Color(36, 47, 65));
        manageOpoidListBtn.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        manageOpoidListBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageOpoidListBtn.setText("Manage Opioids");
        manageOpoidListBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        manageOpoidListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOpoidListBtnActionPerformed(evt);
            }
        });
        jPanel1.add(manageOpoidListBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 160, 70));

        manageEnterpriseJButton.setBackground(new java.awt.Color(36, 47, 65));
        manageEnterpriseJButton.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        manageEnterpriseJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseJButton.setText("Manage Enterprise");
        manageEnterpriseJButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageEnterpriseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 150, 70));

        jLabel1.setText("Selected Node:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 36, -1, -1));

        selectedNodeJLabel.setText("<view_selected_node>");
        jPanel1.add(selectedNodeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 36, -1, -1));

        manageEnterpriseAdminBtn.setBackground(new java.awt.Color(36, 47, 65));
        manageEnterpriseAdminBtn.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        manageEnterpriseAdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseAdminBtn.setText("Manage Enterprise Admin");
        manageEnterpriseAdminBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        manageEnterpriseAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAdminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(manageEnterpriseAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, 70));

        mngPersonBtn.setBackground(new java.awt.Color(36, 47, 65));
        mngPersonBtn.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        mngPersonBtn.setForeground(new java.awt.Color(255, 255, 255));
        mngPersonBtn.setText("Manage Person");
        mngPersonBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mngPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngPersonBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mngPersonBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 150, 70));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Country Admin Work Area");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel6.setBackground(new java.awt.Color(36, 47, 65));
        jLabel6.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/planet_earth-wide.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -140, 3000, 1500));

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(71, 79, 112));

        JTree.setBackground(new java.awt.Color(204, 204, 204));
        JTree.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        JTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                valueChangedAction(evt);
            }
        });
        jScrollPane1.setViewportView(JTree);

        jPanel2.add(jScrollPane1);

        jSplitPane1.setLeftComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed
        if(cNetwork.getNetworkStateList().isEmpty())
            JOptionPane.showMessageDialog(null,"Please add state networks before adding enterprises");
        else
        {
        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer, cNetwork, system);
        userProcessContainer.add("manageEnterpriseJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    private void manageOpoidListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOpoidListBtnActionPerformed
        
        ManageOpioidsJPanel manageEnterpriseJPanel = new ManageOpioidsJPanel(userProcessContainer,system, cNetwork);
        userProcessContainer.add("manageOpioidsJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOpoidListBtnActionPerformed

    private void manageNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButtonActionPerformed
        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(userProcessContainer, cNetwork,system);
        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkJButtonActionPerformed

    private void valueChangedAction(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_valueChangedAction
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) JTree.getLastSelectedPathComponent();
        if (selectedNode != null) {
            selectedNodeJLabel.setText(selectedNode.toString());
        }

    }//GEN-LAST:event_valueChangedAction

    private void manageEnterpriseAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminBtnActionPerformed
         // TODO add your handling code here:
          if(cNetwork.getNetworkStateList().isEmpty())
            JOptionPane.showMessageDialog(null,"Please add state networks before adding enterprises");
        else
        {
         ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(userProcessContainer, cNetwork, system);
        userProcessContainer.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_manageEnterpriseAdminBtnActionPerformed

    private void mngPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngPersonBtnActionPerformed
        // TODO add your handling code here:
        ManagePersonJPanel manageEnterpriseAdminJPanel = new ManagePersonJPanel(userProcessContainer, system, cNetwork);
        userProcessContainer.add("managePersonJPanel", manageEnterpriseAdminJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mngPersonBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree JTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageEnterpriseAdminBtn;
    private javax.swing.JButton manageEnterpriseJButton;
    private javax.swing.JButton manageNetworkJButton;
    private javax.swing.JButton manageOpoidListBtn;
    private javax.swing.JButton mngPersonBtn;
    private javax.swing.JLabel selectedNodeJLabel;
    // End of variables declaration//GEN-END:variables
}
