/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CountryAdminWorkAreas;

import Business.Country.OpioidMedication;
import Business.Country.Person;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Hospital.Patient;
import Business.Hospital.Perscription;
import Business.Hospital.Report;
import Business.LatLong;
import Business.Network.NetworkCountry;
import Business.Network.NetworkState;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import userinterface.GoogleMapAPI.OrganizationLocationJPanel;
import userinterface.HospitalEnterprise.HospitalEnterpriseManageOrganizationJPanel;
import utility.Validator;

/**
 *
 * @author Vignesh Murali
 */
public class ManagePersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private NetworkCountry cNetwork;
    private LatLong latLong;

    /**
     * Creates new form ManagePersonJPanel
     *
     * @param userProcessContainer
     * @param system
     * @param cNetwork
     */
    public ManagePersonJPanel(JPanel userProcessContainer, EcoSystem system, NetworkCountry cNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.cNetwork = cNetwork;
        latLong = new LatLong();
        populatePersonTable();

    }

    public void populateLatLong(LatLong latLong) {
        this.latLong = latLong;
        lattxt.setText(String.valueOf(latLong.getLatitude()));
        longtxt.setText(String.valueOf(latLong.getLongitude()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        personNameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVaccine = new javax.swing.JTable();
        btnnewPerson = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtpatientid = new javax.swing.JTextField();
        idErrLbl = new javax.swing.JLabel();
        nameErrLbl = new javax.swing.JLabel();
        lattxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tblNearestPerson = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        longtxt = new javax.swing.JTextField();
        btnlocation = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(36, 47, 65));
        btnBack.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        btnDelete.setBackground(new java.awt.Color(36, 47, 65));
        btnDelete.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Remove Person from system");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 208, -1));

        personNameTxt.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        personNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                personNameTxtKeyPressed(evt);
            }
        });
        add(personNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 120, -1));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Person");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        tblVaccine.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        tblVaccine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person Name", "Person ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVaccine);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 590, 170));

        btnnewPerson.setBackground(new java.awt.Color(36, 47, 65));
        btnnewPerson.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        btnnewPerson.setForeground(new java.awt.Color(255, 255, 255));
        btnnewPerson.setText("Create Person");
        btnnewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewPersonActionPerformed(evt);
            }
        });
        add(btnnewPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, 150, -1));

        jComboBox1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passportid", "license", "ssn", "license" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 120, -1));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel1.setText("Patient Identification");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, -1, -1));

        txtpatientid.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        add(txtpatientid, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 202, -1));

        idErrLbl.setForeground(new java.awt.Color(255, 51, 51));
        add(idErrLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 428, -1, -1));

        nameErrLbl.setForeground(new java.awt.Color(255, 51, 51));
        add(nameErrLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 388, -1, -1));

        lattxt.setEditable(false);
        lattxt.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        add(lattxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, 178, -1));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel3.setText("Latitude");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 650, -1, -1));

        tblNearestPerson.setBackground(new java.awt.Color(36, 47, 65));
        tblNearestPerson.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        tblNearestPerson.setForeground(new java.awt.Color(255, 255, 255));
        tblNearestPerson.setText("Find nearest Hospitals");
        tblNearestPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblNearestPersonActionPerformed(evt);
            }
        });
        add(tblNearestPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 720, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel4.setText("Longitude");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 680, -1, -1));

        longtxt.setEditable(false);
        longtxt.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        longtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longtxtActionPerformed(evt);
            }
        });
        add(longtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 670, 178, -1));

        btnlocation.setBackground(new java.awt.Color(36, 47, 65));
        btnlocation.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        btnlocation.setForeground(new java.awt.Color(255, 255, 255));
        btnlocation.setText("Set Location");
        btnlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocationActionPerformed(evt);
            }
        });
        add(btnlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 640, -1, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/social-network-media-data-ss-1920.jpg"))); // NOI18N
        jLabel6.setText("jLabel3");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2500, 250));

        jLabel5.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel5.setText("Person Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVaccine.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            Person p = (Person) tblVaccine.getValueAt(selectedRow, 0);
            for (Person per : cNetwork.getPersonDir().getPersonList()) {
                for (NetworkState ns : cNetwork.getNetworkStateList()) {
                    for (Enterprise e : ns.getEnterpriseDirectory().getEnterpriseList()) {
                        for (Organization or : e.getOrganizationDirectory().getOrganizationList()) {
                            if (or instanceof HospitalOrganization) {
                                for (Patient re : ((HospitalOrganization) or).getHosPatientDir().getPatientList()) {
                                    if (re.getUniquePatientId() == p.getPersonId()) {
                                        ((HospitalOrganization) or).getHosPatientDir().getPatientList().remove(re);
                                    }
                                }
                            }

                        }
                    }
                }

            }
            cNetwork.getPersonDir().removePerson(p);

            JOptionPane.showMessageDialog(null, "You have successfully deleted the account");
            populatePersonTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnnewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewPersonActionPerformed
        // TODO add your handling code here:

        boolean existing_person = false;
        if (txtpatientid.getText().equals("")) {
            txtpatientid.setBorder(new LineBorder(Color.red));
            idErrLbl.setText("Person ID cannot be empty.");
            return;
        }
        for (Person per : cNetwork.getPersonDir().getPersonList()) {
            if (txtpatientid.getText().equalsIgnoreCase(per.getPersonId())) {
                txtpatientid.setBorder(new LineBorder(Color.red));
                idErrLbl.setText("Person identification already exists.");
                return;
            }
        }
        if (lattxt.getText().equals("")) {
            lattxt.setBorder(new LineBorder(Color.red));
            idErrLbl.setText("Must set location");
            return;
        }
        if (personNameTxt.getText().equals("")) {
            personNameTxt.setBorder(new LineBorder(Color.red));
            nameErrLbl.setText("Name cannot be empty.");
        } else {
            personNameTxt.setBorder(new LineBorder(Color.black));
            nameErrLbl.setText("");
            txtpatientid.setBorder(new LineBorder(Color.black));
            idErrLbl.setText("");
            for (Person p : cNetwork.getPersonDir().getPersonList()) {
                if (p != null) {
                    if (p.getPersonId() == null || !p.getPersonId().equals(txtpatientid.getText())) {
                        Person v = cNetwork.getPersonDir().addPerson();
                        v.setPersonName(personNameTxt.getText());
                        v.setPersonId(txtpatientid.getText());
                        v.setLatitude(Double.parseDouble(lattxt.getText()));
                        v.setLongitude(Double.parseDouble(longtxt.getText()));
                        existing_person = true;
                        break;
                    } else {
                        existing_person = false;
                    }
                }
            }
            if (cNetwork.getPersonDir().getPersonList().size() == 0) {
                Person v = cNetwork.getPersonDir().addPerson();
                v.setPersonName(personNameTxt.getText());
                v.setPersonId(txtpatientid.getText());
                existing_person = true;
            }
            if (existing_person == false) {
                JOptionPane.showMessageDialog(null, "Person already exists");
            } else {
                JOptionPane.showMessageDialog(null, "Successfully added person");
            }

            populatePersonTable();
        }
    }//GEN-LAST:event_btnnewPersonActionPerformed

    private void personNameTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personNameTxtKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, personNameTxt);
    }//GEN-LAST:event_personNameTxtKeyPressed

    private void tblNearestPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblNearestPersonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVaccine.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            Person p = (Person) tblVaccine.getValueAt(selectedRow, 0);
            ViewNearestHospitalsJPanel manageNearestHospitals = new ViewNearestHospitalsJPanel(userProcessContainer, p, cNetwork);
            userProcessContainer.add("manageNearestHospitals", manageNearestHospitals);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_tblNearestPersonActionPerformed

    private void longtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longtxtActionPerformed

    private void btnlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocationActionPerformed
        // TODO add your handling code here:
        OrganizationLocationJPanel manageGoogleOrgLoc = new OrganizationLocationJPanel(userProcessContainer);
        userProcessContainer.add("manageGoogleOrgLoc", manageGoogleOrgLoc);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnlocationActionPerformed

    public void populatePersonTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblVaccine.getModel();
        dtm.setRowCount(0);
        for (Person vaccine : cNetwork.getPersonDir().getPersonList()) {

            Object[] row = new Object[2];
            row[0] = vaccine;
            row[1] = vaccine.getPersonId();
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnlocation;
    private javax.swing.JButton btnnewPerson;
    private javax.swing.JLabel idErrLbl;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lattxt;
    private javax.swing.JTextField longtxt;
    private javax.swing.JLabel nameErrLbl;
    private javax.swing.JTextField personNameTxt;
    private javax.swing.JButton tblNearestPerson;
    private javax.swing.JTable tblVaccine;
    private javax.swing.JTextField txtpatientid;
    // End of variables declaration//GEN-END:variables
}
