/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CountryAdminWorkAreas;

import Business.Country.OpioidMedication;
import Business.EcoSystem;
import Business.Network.NetworkCountry;
import Business.Sytem.Conditions;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vignesh Murali
 */
public class ManageOpioidsJPanel extends javax.swing.JPanel {
 JPanel userProcessContainer; 
    EcoSystem system;
        private NetworkCountry cNetwork;

    /**
     * Creates new form ManageOpioidsJPanel
     * @param userProcessContainer
     * @param system
     */
    public ManageOpioidsJPanel( JPanel userProcessContainer,
    EcoSystem system, NetworkCountry cNetwork
) {
        initComponents();
         this.userProcessContainer=userProcessContainer; 
         this.system=system;
         this.cNetwork=cNetwork;
         populateVaccineTable();
         populatecombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVaccine = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblwelcome = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        txtVaccineName = new javax.swing.JTextField();
        comboDisease = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        errLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMME = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVaccine.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        tblVaccine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Opioid Name", "Opioid ID", "Conditions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVaccine);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 590, 170));

        btnNew.setBackground(new java.awt.Color(36, 47, 65));
        btnNew.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setText("Create New Opioid");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 820, 150, -1));

        btnBack.setBackground(new java.awt.Color(36, 47, 65));
        btnBack.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        lblwelcome.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        add(lblwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 240, 20));

        btnDelete.setBackground(new java.awt.Color(36, 47, 65));
        btnDelete.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Opioid");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 180, -1));

        txtVaccineName.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        add(txtVaccineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 120, -1));

        comboDisease.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        comboDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiseaseActionPerformed(evt);
            }
        });
        add(comboDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 760, 120, -1));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel1.setText("Condition:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 780, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, -1, -1));

        errLbl.setForeground(new java.awt.Color(255, 51, 51));
        errLbl.setToolTipText("");
        add(errLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 810, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel3.setText("MME (Morphine Milligram Equivlant)");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 690, -1, -1));

        txtMME.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        add(txtMME, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 690, 50, -1));

        updateBtn.setBackground(new java.awt.Color(36, 47, 65));
        updateBtn.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update Opioid");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel4.setText("Manage Opioids");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/tablets_capsules_multi-colored_drug_48978_1920x1080.jpg"))); // NOI18N
        jLabel6.setText("jLabel3");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 2500, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        
        String name = txtVaccineName.getText();
        if(comboDisease.getSelectedItem()==null)
        {
             errLbl.setText("There are no conditions available to add.");
             txtVaccineName.setBorder(new LineBorder(Color.red));
             return;
        }
        if(!cNetwork.getOpioidList().isUniqueOpioid(name))
        {
            errLbl.setText("This opioid already exists in our directory!");
             txtVaccineName.setBorder(new LineBorder(Color.red));
             return;
            
        }
        if(txtMME.getText().equals("")){
            errLbl.setText("Please dont leave MME blank.");
             txtMME.setBorder(new LineBorder(Color.red));
             return;
        }
        if(!name.equals(""))
        {
            errLbl.setText("");
             txtVaccineName.setBorder(new LineBorder(Color.black));
             txtMME.setBorder(new LineBorder(Color.black));
            OpioidMedication v= cNetwork.getOpioidList().addDisease();
             v.setOpioidName(txtVaccineName.getText());
             v.setMmeMultiplier(Float.parseFloat(txtMME.getText()));
            ArrayList<Conditions> conList = v.getConditionList();
            conList.add((Conditions)comboDisease.getSelectedItem());
            v.setConditionList(conList);
            
            populateVaccineTable();
            
           
        }
        else{
             errLbl.setText("Please enter a valid opioid name.");
             txtVaccineName.setBorder(new LineBorder(Color.red));
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow= tblVaccine.getSelectedRow();
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select the row to delete this opioid", "Warning", JOptionPane.WARNING_MESSAGE);
        }
       
        else{
            
            
             if(tblVaccine.getValueAt(selectedRow, 0).toString().equals("Reversal"))
        {
            System.out.println(tblVaccine.getValueAt(selectedRow, 0));
            JOptionPane.showMessageDialog(null, "Cannot remove reversal drug");
            return;
        }

            OpioidMedication p=(OpioidMedication) tblVaccine.getValueAt(selectedRow, 0);
            
            

            cNetwork.getOpioidList().removeDisease(p);

            JOptionPane.showMessageDialog(null, "You have successfully deleted the account");
            populateVaccineTable();
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void comboDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiseaseActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_comboDiseaseActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
           int selectedRow= tblVaccine.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select an opioid", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            if(tblVaccine.getValueAt(selectedRow, 0).toString().equals("Reversal"))
            {
                JOptionPane.showMessageDialog(null, "Cannot update the reversal drug");
                return;
                
            }
             OpioidMedication p=(OpioidMedication) tblVaccine.getValueAt(selectedRow, 0);
      
        UpdateOpioidJPanel manageEnterpriseJPanel = new UpdateOpioidJPanel(userProcessContainer,system, cNetwork,p);
        userProcessContainer.add("manageOpioidsJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    public void populateVaccineTable(){
         DefaultTableModel dtm= (DefaultTableModel) tblVaccine.getModel();
       dtm.setRowCount(0);
       for (OpioidMedication vaccine : cNetwork.getOpioidList().getOpioidList()) {
        
           Object[] row = new Object[3];
           row[0]= vaccine;
           row[1]=vaccine.getOpioidId();
           row[2]=vaccine.getConditionList();
           dtm.addRow(row);
       }  
       }
    
    public void populatecombo(){
        for (Conditions disease : system.getConditionsList().getConditionList()) {
            comboDisease.addItem(disease);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JComboBox comboDisease;
    private javax.swing.JLabel errLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JTable tblVaccine;
    private javax.swing.JTextField txtMME;
    private javax.swing.JTextField txtVaccineName;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
