/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CountryAdminWorkAreas;

import Business.Country.Person;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.LatLong;
import Business.Network.NetworkCountry;
import Business.Network.NetworkState;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author indu
 */
public class ViewNearestHospitalsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewNearestHospitalsJPanel
     */
    private JPanel userProcessContainer;
    private NetworkCountry cNetwork;
    private LatLong latLong;
    private Person p;

    public ViewNearestHospitalsJPanel(JPanel userProcessContainer, Person p, NetworkCountry cNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.cNetwork = cNetwork;
        this.p = p;
        populatePersonTable();
    }

    public void populatePersonTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblHospitals.getModel();
        dtm.setRowCount(0);
        for (NetworkState state : cNetwork.getNetworkStateList()) {
            for (Enterprise ent : state.getEnterpriseDirectory().getEnterpriseList()) {
                if (ent instanceof HospitalEnterprise) {
                    for (Organization orghos : ent.getOrganizationDirectory().getOrganizationList()) {
                        if ((orghos.getLongitude() != 0) && (p.getLatitude() != 0) && (p.getLongitude() != 0)) {
                            double orglat = orghos.getLatitude();
                            double orglong = orghos.getLongitude();
                            double distance = populateDistance(p, orglat, orglong);
                            if (distance <= 10) {
                                System.out.println("distance:"+distance);
                                Object[] row = new Object[3];
                                row[0] = orghos;
                                row[1] = orglat;
                                row[2] = orglong;
                                dtm.addRow(row);
                            }
                        }
                    }
                }
            }
        }
    }

    public double populateDistance(Person p1, double orglat, double orglong) {
        double lat1 = p1.getLatitude();
        double lon1 = p1.getLongitude();
        double lat2 = orglat;
        double lon2 = orglong;

        double theta = lon1 - lon2;
        double dist = Math.sin(deg2rad(lat1)) * Math.sin(deg2rad(lat2)) + Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * Math.cos(deg2rad(theta));
        dist = Math.acos(dist);
        dist = rad2deg(dist);
        dist = dist * 60 * 1.1515;
        return dist;
    }

    private double deg2rad(double deg) {
        return (deg * Math.PI / 180.0);
    }

    private double rad2deg(double rad) {
        return (rad * 180.0 / Math.PI);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospitals = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        tblHospitals.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        tblHospitals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital Name", "Latitude", "longitude"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHospitals);

        btnBack.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack))
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnBack)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHospitals;
    // End of variables declaration//GEN-END:variables
}
