/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PublicStateHealthOrganization;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.NetworkCountry;
import Business.Organization.Organization;
import Business.Organization.ProviderOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.Hospital.HosOrganization.HospitalOrganizationManageUserAccountJPanel;

/**
 *
 * @author sonal
 */
public class PublicStateHealthOrgWorkAreaJPanel extends javax.swing.JPanel {
JPanel userProcessContainer; UserAccount account; Organization organization; Enterprise enterprise; EcoSystem business;NetworkCountry cNetwork;
    /**
     * Creates new form PublicStateHealthOrgWorkAreaJPanel
     */
    public PublicStateHealthOrgWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business,NetworkCountry cNetwork) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.organization=organization;
        this.enterprise=enterprise;
        this.business=business;
        this.cNetwork=cNetwork;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ctryBtn = new javax.swing.JButton();
        countryBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Public State Health Organization");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        ctryBtn.setBackground(new java.awt.Color(36, 47, 65));
        ctryBtn.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        ctryBtn.setForeground(new java.awt.Color(255, 255, 255));
        ctryBtn.setText("State Statistics");
        ctryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctryBtnActionPerformed(evt);
            }
        });
        add(ctryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 343, 66));

        countryBtn.setBackground(new java.awt.Color(36, 47, 65));
        countryBtn.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        countryBtn.setForeground(new java.awt.Color(255, 255, 255));
        countryBtn.setText("Country Statistics");
        countryBtn.setOpaque(false);
        countryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryBtnActionPerformed(evt);
            }
        });
        add(countryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 190, 343, 67));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/senate.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -210, 3000, 1500));
    }// </editor-fold>//GEN-END:initComponents

    private void ctryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctryBtnActionPerformed
        // TODO add your handling code here:
        ViewStateStatistics muajp = new ViewStateStatistics(userProcessContainer,enterprise.getOrganizationDirectory(),business,cNetwork,account);
        userProcessContainer.add("viewCountryStatistics", muajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ctryBtnActionPerformed

    private void countryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryBtnActionPerformed
        // TODO add your handling code here:
        ViewCountryStatistics muajp = new ViewCountryStatistics(userProcessContainer,enterprise.getOrganizationDirectory(),business,cNetwork,account);
        userProcessContainer.add("viewCountryStatistics", muajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_countryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton countryBtn;
    private javax.swing.JButton ctryBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
