/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PublicStateHealthOrganization;

import Business.Country.OpioidMedication;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Hospital.Perscription;
import Business.Hospital.Report;
import Business.Network.NetworkCountry;
import Business.Network.NetworkState;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Vignesh Murali
 */
public class StateStatsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EcoSystem business;
    NetworkState networkState;
    NetworkCountry cNetwork;
    UserAccount account;

    /**
     * Creates new form StateStatsJPanel
     */
    StateStatsJPanel(JPanel userProcessContainer, EcoSystem business, NetworkState networkState, NetworkCountry cNetwork, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.networkState = networkState;
        this.cNetwork = cNetwork;
        this.account = account;
        populateCombo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hospComboBox = new javax.swing.JComboBox();
        backjButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chartJPanel = new javax.swing.JPanel();

        hospComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospComboBoxActionPerformed(evt);
            }
        });

        backjButton1.setBackground(new java.awt.Color(36, 47, 65));
        backjButton1.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        backjButton1.setForeground(new java.awt.Color(255, 255, 255));
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(36, 47, 65));
        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jLabel1.setText("Hospital");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hospComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backjButton1)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(hospComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(chartJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void hospComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospComboBoxActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
        HashMap<String, Integer> hm1 = new HashMap<>();
        
        for (OpioidMedication opioidName : cNetwork.getOpioidList().getOpioidList()) {
            int count=0;
            for (Enterprise e : networkState.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof HospitalEnterprise) {
                    for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                        
                        HospitalOrganization o1 = (HospitalOrganization) hospComboBox.getSelectedItem();
//                        if (account.getUsername().equalsIgnoreCase(o.getName())) {
                            
                            for (Report r : o1.getReportDir().getReportList()) {
                                
                                
                                for(String opioidN: r.getHm().keySet()){
                                    
                                    if(opioidN.equalsIgnoreCase(opioidName.getOpioidName())){
                                        count++;
                                        System.out.println("Counter"+count);
                                        
                                        
                                    }
                                }
                            }

//                        }

                    }
                }
            }
            
            hm1.put(opioidName.getOpioidName(), count);
        }
        
    
        
        Iterator it = hm1.entrySet().iterator();
        while(it.hasNext())
        {
            Map.Entry pair = (Map.Entry)it.next();
            
            
            String key1 = (String) pair.getKey();
            if(key1.equals("Reversal"))
            {
                System.out.println("LOOK HERE"+pair.getKey());
                System.out.println(pair.getValue());
            }
            int val1 = (int) pair.getValue();
            
            barchartdata.setValue(val1, "Number of patients", key1);
            
        }
    
        
         JFreeChart barchart = ChartFactory.createBarChart("Patients per opioid", "Opioid Name", "No. of patients", barchartdata, PlotOrientation.VERTICAL, true, true, true);
        CategoryPlot barch = barchart.getCategoryPlot();
        barch.setRangeGridlinePaint(Color.magenta);
//        ChartFrame frame = new ChartFrame("Patients per Opioid",barchart);
//        frame.setVisible(true);
//        frame.setSize(350,450);
        
        
            ChartPanel barpanel = new ChartPanel(barchart);
        
        chartJPanel.removeAll();
        
        chartJPanel.add(barpanel,BorderLayout.CENTER);
        chartJPanel.repaint();
        chartJPanel.validate();

    }//GEN-LAST:event_hospComboBoxActionPerformed
    void populateCombo() {
        for (Enterprise e : networkState.getEnterpriseDirectory().getEnterpriseList()) {

            if (e instanceof HospitalEnterprise) {
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    hospComboBox.addItem(o);

                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JPanel chartJPanel;
    private javax.swing.JComboBox hospComboBox;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
