/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalEnterprise;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.LatLong;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import userinterface.GoogleMapAPI.OrganizationLocationJPanel;

/**
 *
 * @author sonal
 */
public class HospitalEnterpriseManageOrganizationJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    private LatLong latLong;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public HospitalEnterpriseManageOrganizationJPanel(JPanel userProcessContainer, OrganizationDirectory directory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        latLong = new LatLong();

        populateTable();
        populateCombo();
    }

    private void populateCombo() {
        organizationJComboBox.removeAllItems();
        //  for (Type type : Organization.Type.values()){
        //     if (!type.getValue().equals(Type.HospitalOrganization.getValue()))
        organizationJComboBox.addItem(Type.HospitalOrganization);
        //  }
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();

        model.setRowCount(0);

        for (Organization organization : directory.getOrganizationList()) {
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization;

            model.addRow(row);
        }
    }

    public void populateLatLong(LatLong latLong) {
        this.latLong = latLong;
        lattxt.setText(String.valueOf(latLong.getLatitude()));
        longtxt.setText(String.valueOf(latLong.getLongitude()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        addJButton = new javax.swing.JButton();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        orgNametxtbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        errLbl = new javax.swing.JLabel();
        delBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        lattxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        latlongtxt1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        longtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationJTable.setBackground(new java.awt.Color(36, 47, 65));
        organizationJTable.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        organizationJTable.setForeground(new java.awt.Color(255, 255, 255));
        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);
        if (organizationJTable.getColumnModel().getColumnCount() > 0) {
            organizationJTable.getColumnModel().getColumn(0).setResizable(false);
            organizationJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 480, 92));

        addJButton.setBackground(new java.awt.Color(36, 47, 65));
        addJButton.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        addJButton.setForeground(new java.awt.Color(255, 255, 255));
        addJButton.setText("Add Hospital");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 150, 30));

        organizationJComboBox.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 160, -1));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Organization Type ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        backJButton.setBackground(new java.awt.Color(36, 47, 65));
        backJButton.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 110, 40));

        orgNametxtbox.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        add(orgNametxtbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 200, -1));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        errLbl.setForeground(new java.awt.Color(255, 51, 51));
        add(errLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, -1, -1));

        delBtn.setBackground(new java.awt.Color(36, 47, 65));
        delBtn.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        delBtn.setForeground(new java.awt.Color(255, 255, 255));
        delBtn.setText("Delete Hospital");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        add(delBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 140, 30));

        updateBtn.setBackground(new java.awt.Color(36, 47, 65));
        updateBtn.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update Hospital");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 160, 30));

        lattxt.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        add(lattxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 110, -1));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Set Location");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, -1, 60));

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel3.setText("Latitude");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));
        add(latlongtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 110, -1));

        jLabel5.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel5.setText("Latitude");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        longtxt.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        add(longtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 110, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/ekg.jpeg"))); // NOI18N
        jLabel6.setText("jLabel3");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 2500, 250));

        jLabel7.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel7.setText("Organization Type");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        ArrayList<String> checkEnter = new ArrayList<>();
        for (Organization e : directory.getOrganizationList()) {
            checkEnter.add(e.getName());
        }

        if (checkEnter.contains(orgNametxtbox.getText())) {
            errLbl.setText("Organization exists already.");
            orgNametxtbox.setBorder(new LineBorder(Color.red));
            return;
        }
        if (lattxt.getText().equals("")) {
            lattxt.setBorder(new LineBorder(Color.red));
            errLbl.setText("Must set location");
            return;
        }
        if (orgNametxtbox.getText().equals("")) {
            errLbl.setText("Please enter organization name.");
            orgNametxtbox.setBorder(new LineBorder(Color.red));
            return;
        }
        errLbl.setText("");
        orgNametxtbox.setBorder(new LineBorder(Color.black));

        Type type = (Type) organizationJComboBox.getSelectedItem();
        String name = orgNametxtbox.getText();
        double lat = Double.parseDouble(lattxt.getText());
        double longitude = Double.parseDouble(longtxt.getText());
        directory.createOrganization(type, name,lat,longitude);
        
        
        populateTable();
    }//GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = organizationJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the patient to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            Organization e = (Organization) organizationJTable.getValueAt(selectedRow, 1);

            directory.getOrganizationList().remove(e);

            JOptionPane.showMessageDialog(null, "Hospital is removed");
            populateTable();
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = organizationJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the patient to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            Organization e = (Organization) organizationJTable.getValueAt(selectedRow, 1);
            updateOrganizationJPanel manageOrganizationJPanel = new updateOrganizationJPanel(userProcessContainer, directory, e);
            userProcessContainer.add("HospitalManageOrganizationJPanel", manageOrganizationJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        OrganizationLocationJPanel manageGoogleOrgLoctwo = new OrganizationLocationJPanel(userProcessContainer);
        userProcessContainer.add("manageGoogleOrgLoctwo", manageGoogleOrgLoctwo);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton delBtn;
    private javax.swing.JLabel errLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField latlongtxt1;
    private javax.swing.JTextField lattxt;
    private javax.swing.JTextField longtxt;
    private javax.swing.JTextField orgNametxtbox;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
