/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital.HosOrganization;

import Business.Country.OpioidMedication;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Hospital.PTConditionsDirectory;
import Business.Network.NetworkCountry;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.Sytem.Conditions;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sonal
 */
public class AddPTConditionsJPanel extends javax.swing.JPanel {
 JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
     Enterprise enterprise;
    HospitalOrganization organization;
    /**
     * Creates new form AddPTConditionsJPanel
     */
   

    public AddPTConditionsJPanel(JPanel userProcessContainer, UserAccount account, HospitalOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
         this.userProcessContainer=userProcessContainer; 
         this.system=system;
         this.organization=organization;
         this.enterprise=enterprise;
         populatecombo();
         populateTable();
    }
  
    public void populatecombo(){
        for (Conditions disease : system.getConditionsList().getConditionList()) {
            comboDisease.addItem(disease);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboDisease = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ptconditionTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboDisease.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        comboDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiseaseActionPerformed(evt);
            }
        });
        add(comboDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 120, -1));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Set Health Conditions as Physical Therapy conditions");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        ptconditionTable.setBackground(new java.awt.Color(36, 47, 65));
        ptconditionTable.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        ptconditionTable.setForeground(new java.awt.Color(255, 255, 255));
        ptconditionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Physical Therapy Conditions"
            }
        ));
        jScrollPane1.setViewportView(ptconditionTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, 117));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 100, -1));

        backjButton1.setBackground(new java.awt.Color(36, 47, 65));
        backjButton1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        backjButton1.setForeground(new java.awt.Color(255, 255, 255));
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 112, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/maxresdefault.jpg"))); // NOI18N
        jLabel6.setText("jLabel3");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2500, 250));

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jLabel2.setText("Condition:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Conditions c= (Conditions) comboDisease.getSelectedItem();
        System.out.println("userinterface.Hospital.HosOrganization.AddPTConditionsJPanel.jButton1ActionPerformed()");
        if(organization.getPtConditions()==null){
             System.out.println("hi");
            organization.setPtConditions(new PTConditionsDirectory());
        }
        
        ArrayList<String> validatePT = new ArrayList<>();
        for(Conditions cond : organization.getPtConditions().getConditionList())
        {
            validatePT.add(cond.getDiseaseName());
            
        }
        if(validatePT.contains(c.getDiseaseName()))
            JOptionPane.showMessageDialog(null,"This condition has already been added as a physical therapy condition");
        else{
        Conditions cond = organization.getPtConditions().addCondition();
        
        cond.setDiseaseName(c.getDiseaseName());

         
       populateTable();
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiseaseActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboDiseaseActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed
public void populateTable()
{
     DefaultTableModel dtm= (DefaultTableModel) ptconditionTable.getModel();
     dtm.setRowCount(0);
       for (Conditions con : organization.getPtConditions().getConditionList()) {
        
           Object[] row = new Object[2];
           row[0]= con;
           row[1]=con.getDiseaseName();
           dtm.addRow(row);
       }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JComboBox comboDisease;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ptconditionTable;
    // End of variables declaration//GEN-END:variables
}
