/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hospital.HosOrganization;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Hospital.Doctor;
import Business.Hospital.Patient;
import Business.Organization.HospitalOrganization;
import Business.Role.DoctorRole;
import Business.Role.PhysicalTherapyRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author sonal
 */
public class ViewDocStatisticsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDocStatisticsJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    HospitalOrganization organization;
    Enterprise enterprise;
    EcoSystem business;
DefaultCategoryDataset barchartdata ;
    public ViewDocStatisticsJPanel(JPanel userProcessContainer, UserAccount account, HospitalOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.business = business;
        this.organization = organization;

        populateDoctorViolationComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        firedocDropdown = new javax.swing.JComboBox();
        violBtn = new javax.swing.JButton();
        chartJPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Doctor Violation Statistics");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 350, 30));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Suspend Doctor");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        firedocDropdown.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        add(firedocDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 248, 154, -1));

        violBtn.setBackground(new java.awt.Color(36, 47, 65));
        violBtn.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        violBtn.setForeground(new java.awt.Color(255, 255, 255));
        violBtn.setText("Violators Graph");
        violBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                violBtnActionPerformed(evt);
            }
        });
        add(violBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        chartJPanel.setBackground(new java.awt.Color(204, 204, 204));
        add(chartJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 800, 430));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/bar-graphs-3d-wallpaper.jpg"))); // NOI18N
        jLabel7.setText("jLabel3");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-420, -1600, 2500, 1820));

        backjButton1.setBackground(new java.awt.Color(36, 47, 65));
        backjButton1.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        backjButton1.setForeground(new java.awt.Color(255, 255, 255));
        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 112, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void violBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_violBtnActionPerformed
        // TODO add your handling code here:
        
           barchartdata = new DefaultCategoryDataset();
          
        for(Doctor d:organization.getHosDoctorDir().getDoctorList())
        {
              
                    System.out.println("data"+d.getViolationCount()+d.getDocName());
                    barchartdata.setValue(d.getViolationCount(), "Violations", d.getDocName());
                
        }
        
        JFreeChart barchart = ChartFactory.createBarChart("Doctor Violations", "Doctor Name", "No. of Violations", barchartdata, PlotOrientation.VERTICAL, true, true, true);
        CategoryPlot barch = barchart.getCategoryPlot();
        barch.setRangeGridlinePaint(Color.red);
//        ChartFrame frame = new ChartFrame("jfreechart test",barchart);
//        frame.setVisible(true);
//        frame.setSize(350,450);
        ChartPanel barpanel = new ChartPanel(barchart);
        
        chartJPanel.removeAll();
        chartJPanel.add(barpanel, BorderLayout.CENTER);
        chartJPanel.validate();
        System.out.println("reached here");
        
        
    }//GEN-LAST:event_violBtnActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JPanel chartJPanel;
    private javax.swing.JComboBox firedocDropdown;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton violBtn;
    // End of variables declaration//GEN-END:variables

    private void populateDoctorViolationComboBox() {
        firedocDropdown.removeAllItems();
        for (Doctor doc : organization.getHosDoctorDir().getDoctorList()) {
            if (doc.getViolationCount() >0) {
                firedocDropdown.addItem(doc);
            }

        }
    }

}
